displayName=TzHaar Reskin
compatibleVersion=1.0
author=117 HD
description=Reskins the TzHaar environment to match the orange graphics that were introduced with the HD update in RS3. 
support=https://github.com/Mark7625/resource-packs/issues
packType=ADDON
tags=TzHaar,Legacy,Skin,117 HD
