displayName=Legacy Theatre of Blood
compatibleVersion=1.0
author=117 HD
description=Previously, Theatre of Blood used to look a whole lot more blue. This option brings back that same old look.
support=https://github.com/Mark7625/resource-packs/issues
packType=ADDON
tags=Theatre of Blood,Legacy,117 HD
