dynamicLights=NONE
tiledLighting=false
projectileLights=false
npcLights=false
shadowMode=OFF
enableShadowTransparency=false
normalMapping=false
parallaxOcclusionMappingToggle=false
fogDepthMode=USER_DEFINED
fogDepth=1
groundFog=1
objectTextures=false
groundTextures=false
groundBlending=false